<?php
namespace App\Controller;

use App\Controller\AppController;
use Cake\Core\Configure;

/**
 * Guesses Controller
 *
 * @property \App\Model\Table\GuessesTable $Guesses
 * @property \App\Controller\Component\FactorsComponent Factors
 */
class GuessesController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadComponent('Factors');
    }

    /**
     * Add method
     *
     * @param $numberId Number id
     * @return \Cake\Network\Response|void Redirects on successful add, renders view otherwise.
     */
    public function add($numberId)
    {
        $this->request->allowMethod('post');
        $data = ['value' => $this->request->data['value'], 'number_id' => $numberId];
        $number = $this->Guesses->Numbers->get($numberId, ['contain' => 'Guesses']);
        foreach ($number->guesses as $guess) {
            if ($guess->value == $data['value']) {
                echo json_encode([
                    'value' => $guess->value,
                    'result' => [false, 'You have already guessed this number'],
                ]);
                die();
            }
        }
        $guess = $this->Guesses->patchEntity($this->Guesses->newEntity(), $data);
        if ($number->value == $data['value']) {
            $guess->set('number', $number->set('points_awarded',
                pow(Configure::read('gameLevels')[$number->difficulty], .7) / (count($number->guesses) + 1
            )));
        }
        $guess = $this->Guesses->save($guess);
        echo json_encode([
            'value' => $guess->value,
            'result' => $this->Factors->compare($number->value, $guess->value),
        ]);
        die();
    }

}
